# quotes.py

movie_quotes = [
    "May the Force be with you. - Star Wars",
    "I'm gonna make him an offer he can't refuse. - The Godfather",
    "Why so serious? - The Dark Knight",
    "I am inevitable. - Avengers: Endgame",
    "I'll be back. - The Terminator",
    "Hasta la vista, baby. - Terminator 2",
    "With great power comes great responsibility. - Spider-Man",
    "You talking to me? - Taxi Driver",
    "Say hello to my little friend! - Scarface",
    "I feel the need — the need for speed! - Top Gun",
    "To infinity and beyond! - Toy Story",
    "I'm king of the world! - Titanic",
    "Life is like a box of chocolates. - Forrest Gump",
    "You can’t handle the truth! - A Few Good Men",
    "Bond. James Bond. - Dr. No",
    "Here's looking at you, kid. - Casablanca",
    "This is Sparta! - 300",
    "Freedom! - Braveheart",
    "I'm walking here! - Midnight Cowboy",
    "Keep your friends close, but your enemies closer. - The Godfather Part II",
    "It's not who I am underneath, but what I do that defines me. - Batman Begins",
    "You either die a hero or live long enough to see yourself become the villain. - The Dark Knight",
    "Just keep swimming. - Finding Nemo",
    "Houston, we have a problem. - Apollo 13",
    "They may take our lives, but they’ll never take our freedom! - Braveheart",
    "I see dead people. - The Sixth Sense",
    "Nobody puts Baby in a corner. - Dirty Dancing",
    "You complete me. - Jerry Maguire",
    "There's no place like home. - The Wizard of Oz",
    "I volunteer as tribute! - The Hunger Games",
    "I'm Batman. - Batman",
    "It’s a trap! - Star Wars: Return of the Jedi",
    "I'm not a smart man, but I know what love is. - Forrest Gump",
    "Why did it have to be snakes? - Indiana Jones",
    "You’re gonna need a bigger boat. - Jaws",
    "Roads? Where we're going, we don't need roads. - Back to the Future",
    "That’ll do, pig. That’ll do. - Babe",
    "Here's Johnny! - The Shining",
    "I'm having an old friend for dinner. - The Silence of the Lambs",
    "I drink your milkshake! - There Will Be Blood",
    "Are you not entertained? - Gladiator",
    "I wish I knew how to quit you. - Brokeback Mountain",
    "Wakanda forever! - Black Panther",
    "We are Groot. - Guardians of the Galaxy",
    "You're a wizard, Harry. - Harry Potter",
    "Run, Forrest, run! - Forrest Gump",
    "You shall not pass! - The Lord of the Rings",
    "I am Iron Man. - Iron Man / Endgame",
    "Just when I thought I was out, they pull me back in. - The Godfather Part III"
]
